spring:
  application:
    name: reverseword
  cloud:
    discovery:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8088"

#server:
#  port: 8083
#
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    hostname: localhost
##    preferIpAddress: true
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
